### PR TITLE
 Added functionality to retrieve weighted scores

### PR DESCRIPTION
**Pull request by sankettangade**

### CODE REVIEW

**Comment by dbaidya9006** [comment]
Hi @sankettangade, since get_weighted_score is actually getting the proper symbol needed for calculation, these methods could be more descriptive of their responsibilities. 

Maybe something like the following?:

```
 def get_weighted_score(assignment, scores)
    # finds the associated assignment questionnaire and records the questionnaire_weight value
    aq_weight = assignment_questionnaires.find_by(assignment_id: assignment.id).questionnaire_weight
    symbol = get_questionnaire_symbol(assignment)
    # finds average score based on scores passed in parameter
    avg_score = scores.dig(symbol, :scores, :avg)
    # calculates weighted score
    avg_score.nil? ? 0 : (avg_score * aq_weight / 100.0)

  end

  # identifies the symbol needed to calculate the weighted score
  def get_questionnaire_symbol(assignment)
    # sets used_in_round to true if the associated Assignment Questionnaire has a value in the used_in_round column
    used_in_round = AssignmentQuestionnaire.find_by(assignment_id: assignment.id, questionnaire_id: id)&.used_in_round
    # sets symbol based on whether the associated Assignment Questionnaire has a value in the used_in_round column
    questionnaire_symbol = used_in_round ? "#{symbol}#{used_in_round}".to_sym : symbol
  end
```

What do you think?

**Comment by sankettangade** [comment]
Yes, @dbaidya9006  sounds good. We can implement this

**Comment by dbaidya9006** [comment]
@sankettangade LGTM! Just wondering whether you were still planning on implementing the changes discussed above or would rather keep it as is.

**Review by dbaidya9006 — APPROVED** [review]
Functionality works. IMO there's room for improvement with the method names but I'll leave that up to you! LGTM, thanks

**Pull request merged**
